### ISSUE TITLE
Solution of "RecursionError: maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by YanqiDai** [RUC-GSAI/YuLan-Chat#2]
It may be an issue with the tokenizers version. Please change transformers.AutoTokenizer to transformers.LlamaTokenizer at 26th line in inference.py file.

**Comment by forcemeter** [comment]
same issue, and your answer is works! thanks.

**Comment by Lancelot39** [comment]
Maybe this issue derives from the version of transformers and tokenizers. You can refer to our recommended versions in requirements.txt as:

transformers>=4.28.1
tokenizers==0.13.3

Anyway, your mentioned solution is also a nice way to address this problem instead of repreparing the environment, just requiring to revise the inference.py. We thank your kindly sharing such a more convenient solution here.
:)


> It may be an issue with the tokenizers version. Please change transformers.AutoTokenizer to transformers.LlamaTokenizer at 26th line in inference.py file.
